
/*
 * 
 */

package org.apache.mdm_async_soap_http;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-07-14T13:15:58.954-07:00
 * Generated source version: 2.4.0
 * 
 */


@WebServiceClient(name = "SOAPService", 
                  wsdlLocation = "mdm_async.wsdl",
                  targetNamespace = "http://apache.org/mdm_async_soap_http") 
public class SOAPService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://apache.org/mdm_async_soap_http", "SOAPService");
    public final static QName SoapPort = new QName("http://apache.org/mdm_async_soap_http", "SoapPort");
    static {
        URL url = null;
        try {
            url = new URL("mdm_async.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SOAPService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:src/main/resources/mdm_async.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SOAPService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SOAPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SOAPService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns DeviceEnrollment
     */
    @WebEndpoint(name = "SoapPort")
    public DeviceEnrollment getSoapPort() {
        return super.getPort(SoapPort, DeviceEnrollment.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DeviceEnrollment
     */
    @WebEndpoint(name = "SoapPort")
    public DeviceEnrollment getSoapPort(WebServiceFeature... features) {
        return super.getPort(SoapPort, DeviceEnrollment.class, features);
    }

}
