-- http://en.wikipedia.org/wiki/IOS_version_history
CREATE TABLE IF NOT EXISTS APPL_DEVICE_INFO (
  ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  UDID VARCHAR(40),
  DEVICE_NAME VARCHAR(30),
  IOS_VERSION VARCHAR(8),
  IOS_BUILD VARCHAR(20),
  MODEL_NAME VARCHAR(60),
  MODEL_NUMBER VARCHAR(10),
  SERIAL_NUMBER VARCHAR(11),
  IMEI VARCHAR(15),
  MODEM_FIRMWARE VARCHAR(10),
PRIMARY KEY(ID)
);
