
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.example.hosted.impl;

import com.example.mdm.persistence.device.AppleDeviceInfo;
import com.example.mdm.service.AppleDeviceInfoService;
import org.apache.mdm_async_soap_http.DeviceEnrollment;

import java.util.logging.Logger;
import java.util.concurrent.Future;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.Response;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-07-14T13:15:58.886-07:00
 * Generated source version: 2.4.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "SOAPService",
                      portName = "SoapPort",
                      targetNamespace = "http://apache.org/mdm_async_soap_http",
                      wsdlLocation = "mdm_async.wsdl",
                      endpointInterface = "org.apache.mdm_async_soap_http.DeviceEnrollment")
                      
public class DeviceEnrollmentImpl implements DeviceEnrollment {


    private AppleDeviceInfoService deviceInfoService;

    private static final Logger LOG = Logger.getLogger(DeviceEnrollmentImpl.class.getName());

    /* (non-Javadoc)
     * @see org.apache.mdm_async_soap_http.DeviceEnrollment#deviceInfoAsync(java.lang.String  requestType )*
     */
    public Response<org.apache.mdm_async_soap_http.types.DeviceInfoResponse> deviceInfoAsync(java.lang.String requestType) { 
       return null;
       /* not called */
    }

    /* (non-Javadoc)
     * @see org.apache.mdm_async_soap_http.DeviceEnrollment#deviceInfoAsync(java.lang.String  requestType ,)AsyncHandler<org.apache.mdm_async_soap_http.types.DeviceInfoResponse>  asyncHandler )*
     */
    public Future<?> deviceInfoAsync(java.lang.String requestType,AsyncHandler<org.apache.mdm_async_soap_http.types.DeviceInfoResponse> asyncHandler) { 
       return null;
       /* not called */
    }

    /* (non-Javadoc)
     * @see org.apache.mdm_async_soap_http.DeviceEnrollment#deviceInfo(java.lang.String  requestType )*
     */
    public String deviceInfo(String id) {

        AppleDeviceInfo deviceInfo = deviceInfoService.getAppleDeviceInfo(Integer.parseInt(id));

        return "Get DeviceName: " + deviceInfo.getDeviceName();

    }

    public void setDeviceInfoService(final AppleDeviceInfoService service) {
        deviceInfoService = service;
    }
}
